# Generated by Django 2.2 on 2020-09-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datakaryawan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='alamat',
            field=models.TextField(default=''),
        ),
    ]
