# Generated by Django 2.2 on 2020-09-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stokkopi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Stokkopi',
        ),
    ]
