# Generated by Django 2.2 on 2020-09-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Print',
        ),
    ]
