# Generated by Django 2.2 on 2020-09-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_delete_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='desc',
            field=models.TextField(default=0),
        ),
    ]
