# Generated by Django 2.2 on 2020-09-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200827_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='jenisobat',
            new_name='altitudes',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='merk_coffe',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='quantity',
            new_name='process',
        ),
        migrations.AddField(
            model_name='task',
            name='roasteds',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='type_coffe',
            field=models.TextField(default=''),
        ),
    ]
