# Generated by Django 2.2 on 2020-09-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prod',
            name='stok',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
