# Generated by Django 2.2 on 2020-09-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('brg', models.TextField(default='')),
                ('jmlh', models.TextField(default='')),
                ('price', models.TextField(default='')),
            ],
        ),
    ]
