# Generated by Django 2.2 on 2020-09-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='price',
        ),
    ]
