# Generated by Django 2.2 on 2020-09-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Alat',
        ),
    ]
