# Generated by Django 2.2 on 2020-09-17 10:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('qty', models.IntegerField(default='')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membeli', to='customers.Cust')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terjual', to='products.Prod')),
            ],
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sale')),
            ],
        ),
    ]
